spring:
 application:
   name: gateway
 cloud:
   gateway:
     routes:
       - id: search
         uri: http://localhost:9001
         predicates:
           - Path=/search/**

       - id: payment
         uri : http://localhost:9003
         predicates:
             - Path=/payment/**

       - id: assistance
         uri: http://localhost:9004
         predicates:
             - Path=/assistance/**

       - id: booking
         uri: http://localhost:9002
         predicates:
             - Path=/**
